### ISSUE TITLE
More recent .vdi file

### ISSUE THREAD

**Issue by expertcoder** [poflynn/AMZN2Vagrant#2]
Is the documentation pointing to an old VDI file?

Perhaps this one is more recent?

https://cdn.amazonlinux.com/os-images/2.0.20181114/virtualbox/

Thanks

**Comment by poflynn** [comment]
Looks newer ok, should work,. No doubt they'll be coming out with newer versions all the time. Feel free to submit a PR ;-)

**Comment by expertcoder** [comment]
I managed to get this working with the latest image. I have updated several things in the documentation based of my experience, hopefully things are a little clearer

Pull request: https://github.com/poflynn/AMZN2Vagrant/pull/3

Thanks

**Comment by expertcoder** [comment]
Pull request merged and documentation updated.
